// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// SSR-safe storage fallback
const isBrowser = typeof window !== "undefined";
const storage = isBrowser
  ? window.localStorage
  : ({
      getItem: () => null,
      setItem: () => {},
      removeItem: () => {},
      key: () => null,
      length: 0,
      clear: () => {},
    } as unknown as Storage);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabaseSingleton: ReturnType<typeof createClient<Database>> | null = null;

export function getSupabase() {
  if (supabaseSingleton) return supabaseSingleton;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    if (!isBrowser) {
      // SSR/Build-safe stub for auth session retrieval
      return {
        auth: {
          getSession: async () => ({ data: { session: null } }),
        },
      } as unknown as ReturnType<typeof createClient<Database>>;
    }
    throw new Error(
      "Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY"
    );
  }

  supabaseSingleton = createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {
        storage,
        persistSession: true,
        autoRefreshToken: true,
      },
    }
  );
  return supabaseSingleton;
}
