// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phmbpoacpivuqlmjnnoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBobWJwb2FjcGl2dXFsbWpubm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDY1MzksImV4cCI6MjA2NTU4MjUzOX0.bUFjOWBDgltEXrrhuiYOvAX9kr4P60OooH8Bfk65jJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});